services:
  amico_db:
    container_name: amico_db
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


  trovaunamico_app:
    container_name: trovaunamico_app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://amico_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      GOOGLE_CLIENT_ID: 336141363392-32g4dbjqcmtejtes3cji061aucn9upab.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      SPRING_SENDGRID_API_KEY: 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
      SPRING_SENDGRID_SENDER_EMAIL: "noreply.trovaunamico@gmail.com"
    depends_on:
      - amico_db

volumes:
  pgdata: {}
