spring.application.name=TrovaUnAmico
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sendgrid.sender-email=noreply.trovaunamico@gmail.com
spring.sendgrid.api-key=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
spring.security.oauth2.client.registration.google.client-id=336141363392-32g4dbjqcmtejtes3cji061aucn9upab.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
security.oauth2.client.provider.google.user-name-attribute=sub